monolog:
    channels:
        - honey_pot
        - discord_oauth
    handlers:
        discord_oauth:
            level: info
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/discord-oauth.%kernel.environment%.log'
            channels: [discord_oauth]
        honeypot:
            level: info
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/honeypot.%kernel.environment%.log'
            channels: [honey_pot]
        security:
            level: debug
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/security.%kernel.environment%.log'
            channels: [security]
        main:
            level: debug
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            channels: 
                - '!event'
                - '!security'
                - '!honey_pot'
                - '!discord_oauth'
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
